In [1]:
from google.colab import files
uploaded = files.upload()

Saving insurance.xlsx to insurance.xlsx


# Assignment 2
# 1. Handle the Null value.
# 2. Encode using the replace method.
# 3. Use three types of encoding techniques for all the columns which contains  categorical data.
# 4. You have to use loop while encoding.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_excel("insurance.xlsx")

In [4]:
df.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [9]:
df.isnull().sum() #There is no NaN value

age         0
gender      0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

# Handle the Null value

In [11]:
Mean_bmi=df.bmi.mean()
Mean_bmi

np.float64(30.66339686098655)

In [12]:
df.bmi=df.bmi.fillna(Mean_bmi)
df.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [14]:
df1=df.copy()
df2=df.copy()
df3=df.copy()
df4=df.copy()
df5=df.copy()
df6=df.copy()
df7=df.copy()
df8=df.copy()
df9=df.copy()
df10=df.copy()
df11=df.copy()
df12=df.copy()
df13=df.copy()
df14=df.copy()


# Without Encoding(Replacement Method)

In [15]:
df1.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [16]:
df1.gender.unique()

array(['female', 'male'], dtype=object)

In [17]:
df1.gender=df1.gender.replace(['female', 'male'],[0,1])

/tmp/ipython-input-17-3283691020.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.gender=df1.gender.replace(['female', 'male'],[0,1])


In [18]:
df1.smoker.unique()

array(['yes', 'no'], dtype=object)

In [19]:
df1.smoker=df1.smoker.replace(['yes', 'no'],[0,1])

/tmp/ipython-input-19-3440361194.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.smoker=df1.smoker.replace(['yes', 'no'],[0,1])


In [20]:
df1.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [21]:
df1.region=df1.region.replace(['southwest', 'southeast', 'northwest', 'northeast'],[0,1,2,3])

/tmp/ipython-input-21-3692017708.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1.region=df1.region.replace(['southwest', 'southeast', 'northwest', 'northeast'],[0,1,2,3])


In [23]:
df1.head()

age  gender     bmi  children  smoker  region      charges
0   19       0  27.900         0       0       0  16884.92400
1   18       1  33.770         1       1       1   1725.55230
2   28       1  33.000         3       1       1   4449.46200
3   33       1  22.705         0       1       2  21984.47061
4   32       1  28.880         0       1       2   3866.85520

In [25]:
df1.corr()

age    gender       bmi  children    smoker    region   charges
age       1.000000 -0.020856  0.109272  0.042469  0.025019 -0.002127  0.299008
gender   -0.020856  1.000000  0.046371  0.017163 -0.076185 -0.004588  0.057292
bmi       0.109272  0.046371  1.000000  0.012759 -0.003750 -0.157566  0.198341
children  0.042469  0.017163  0.012759  1.000000 -0.007673 -0.016569  0.067998
smoker    0.025019 -0.076185 -0.003750 -0.007673  1.000000 -0.002181 -0.787251
region   -0.002127 -0.004588 -0.157566 -0.016569 -0.002181  1.000000  0.006208
charges   0.299008  0.057292  0.198341  0.067998 -0.787251  0.006208  1.000000

# Label Encoding

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


In [29]:
df2.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [33]:
df2.gender=le.fit_transform(df2.gender)

In [30]:
df2.smoker=le.fit_transform(df2.smoker)

In [31]:
df2.region=le.fit_transform(df2.region)

In [34]:
df2.head()

age  gender     bmi  children  smoker  region      charges
0   19       0  27.900         0       1       3  16884.92400
1   18       1  33.770         1       0       2   1725.55230
2   28       1  33.000         3       0       2   4449.46200
3   33       1  22.705         0       0       1  21984.47061
4   32       1  28.880         0       0       1   3866.85520

# Label Encoding using Loop


In [35]:
for col in df3.columns:
  if df3[col].dtype == np.number:
    continue
  else:
    df3[col]=le.fit_transform(df3[col])

/tmp/ipython-input-35-2289898119.py:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df3[col].dtype == np.number:
/tmp/ipython-input-35-2289898119.py:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df3[col].dtype == np.number:
/tmp/ipython-input-35-2289898119.py:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df3[col].dtype == np.number:
/tmp/ipython-input-35-2289898119.py:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df3[col].dtype == np.number:
/tmp/ipython-input-35-2289898119.py:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dty

In [36]:
df3.head()

age  gender     bmi  children  smoker  region      charges
0    1       0  27.900         0       1       3  16884.92400
1    0       1  33.770         1       0       2   1725.55230
2   10       1  33.000         3       0       2   4449.46200
3   15       1  22.705         0       0       1  21984.47061
4   14       1  28.880         0       0       1   3866.85520

#Another way of Label Encoding without any warnings(Best)

In [38]:
from pandas.core.dtypes.common import is_numeric_dtype

In [39]:
for col in df4.columns:
  if is_numeric_dtype(df4[col]):
    continue
  else:
    df4[col]=le.fit_transform(df4[col])

In [40]:
df4.head()

age  gender     bmi  children  smoker  region      charges
0   19       0  27.900         0       1       3  16884.92400
1   18       1  33.770         1       0       2   1725.55230
2   28       1  33.000         3       0       2   4449.46200
3   33       1  22.705         0       0       1  21984.47061
4   32       1  28.880         0       0       1   3866.85520

# One Hot Encoding


In [53]:
df5.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [48]:
dummy1=pd.get_dummies(df5['gender'],prefix='gender',dtype=int)
dummy1.head()

gender_female  gender_male
0              1            0
1              0            1
2              0            1
3              0            1
4              0            1

In [54]:
df5.drop(["gender","smoker","region"],axis=1,inplace=True)

In [55]:
df5.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

# Dummy Variable Trap


In [57]:
dummy1=pd.get_dummies(df6['gender'],drop_first=True,prefix='gender',dtype=int)
dummy1.head()

gender_male
0            0
1            1
2            1
3            1
4            1

In [58]:
dummy2=pd.get_dummies(df6['smoker'],drop_first=True,prefix='smoker',dtype=int)
dummy2.head()

smoker_yes
0           1
1           0
2           0
3           0
4           0

In [60]:
dummy3=pd.get_dummies(df6['region'],drop_first=True,prefix='region',dtype=int)
dummy3.head()

region_northwest  region_southeast  region_southwest
0                 0                 0                 1
1                 0                 1                 0
2                 0                 1                 0
3                 1                 0                 0
4                 1                 0                 0

In [62]:
df6=pd.concat([df5,dummy1,dummy2,dummy3],axis=1)
df6.head()

age     bmi  children      charges  gender_male  smoker_yes  \
0   19  27.900         0  16884.92400            0           1   
1   18  33.770         1   1725.55230            1           0   
2   28  33.000         3   4449.46200            1           0   
3   33  22.705         0  21984.47061            1           0   
4   32  28.880         0   3866.85520            1           0   

   region_northwest  region_southeast  region_southwest  
0                 0                 0                 1  
1                 0                 1                 0  
2                 0                 1                 0  
3                 1                 0                 0  
4                 1                 0                 0

#One Hot Encoding using Loop


In [80]:
df7.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [77]:
cols=['gender','smoker','region']
for col in cols:
  dummy4=pd.get_dummies(df7[col],prefix=col,drop_first=True,dtype=int)
  df8 = pd.concat([df8.drop(col, axis=1), dummy4], axis=1)

In [81]:
df8.head()

age     bmi  children      charges  gender_male  smoker_yes  \
0   19  27.900         0  16884.92400            0           1   
1   18  33.770         1   1725.55230            1           0   
2   28  33.000         3   4449.46200            1           0   
3   33  22.705         0  21984.47061            1           0   
4   32  28.880         0   3866.85520            1           0   

   region_northwest  region_southeast  region_southwest  
0                 0                 0                 1  
1                 0                 1                 0  
2                 0                 1                 0  
3                 1                 0                 0  
4                 1                 0                 0

# Ordinal Encoding


In [111]:
from sklearn.preprocessing import OrdinalEncoder

In [110]:
df9.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [89]:
gender=df9.gender.unique()
gender

array(['female', 'male'], dtype=object)

In [90]:
smoker=df9.smoker.unique()
smoker

array(['yes', 'no'], dtype=object)

In [91]:
region=df9.region.unique()
region

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [93]:
od=OrdinalEncoder(categories=[gender,smoker,region])
od

OrdinalEncoder(categories=[array(['female', 'male'], dtype=object),
                           array(['yes', 'no'], dtype=object),
                           array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)])

In [96]:
encoded_valu=od.fit_transform(df9[['gender','smoker','region']])
encoded_valu

[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [0. 1. 1.]
 [0. 1. 0.]
 [0. 0. 2.]]


In [97]:
encoded_valu=pd.DataFrame(encoded_valu,columns=['gender','smoker','region'])
encoded_valu.head()

gender  smoker  region
0     0.0     0.0     0.0
1     1.0     1.0     1.0
2     1.0     1.0     1.0
3     1.0     1.0     2.0
4     1.0     1.0     2.0

In [112]:
df9=pd.concat([df9.drop(['gender','smoker','region'],axis=1),encoded_valu],axis=1)
df9.head()

age     bmi  children      charges  gender  smoker  region
0   19  27.900         0  16884.92400     0.0     0.0     0.0
1   18  33.770         1   1725.55230     1.0     1.0     1.0
2   28  33.000         3   4449.46200     1.0     1.0     1.0
3   33  22.705         0  21984.47061     1.0     1.0     2.0
4   32  28.880         0   3866.85520     1.0     1.0     2.0

# Ordinal Encoder Using Loop


In [128]:
df10.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [129]:
gender1=['female','male']
smoker1 = ['no', 'yes']
region1 = ['northeast', 'northwest', 'southeast', 'southwest']


In [130]:
cols=['gender','smoker','region']
category_dict = {
    'gender': gender1,
    'smoker': smoker1,
    'region': region1
}
for col in cols:
  oe2=OrdinalEncoder(categories=[category_dict[col]])
  df10[col]=oe2.fit_transform(df10[[col]])


In [132]:
df10.head()

age  gender     bmi  children  smoker  region      charges
0   19     0.0  27.900         0     1.0     3.0  16884.92400
1   18     1.0  33.770         1     0.0     2.0   1725.55230
2   28     1.0  33.000         3     0.0     2.0   4449.46200
3   33     1.0  22.705         0     0.0     1.0  21984.47061
4   32     1.0  28.880         0     0.0     1.0   3866.85520

# Ordinal Encoding (Easy)


In [133]:
df11.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [136]:
gender2=['female','male']
smoker2 = ['no', 'yes']
region2 = ['northeast', 'northwest', 'southeast', 'southwest']
category_dict = {
    'gender': gender2,
    'smoker': smoker2,
    'region': region2
}
oe = OrdinalEncoder(categories=[category_dict['gender'],category_dict['smoker'],category_dict['region']])
df11[['gender', 'smoker', 'region']] = oe.fit_transform(df11[['gender', 'smoker', 'region']])

In [137]:
df11.head()

age  gender     bmi  children  smoker  region      charges
0   19     0.0  27.900         0     1.0     3.0  16884.92400
1   18     1.0  33.770         1     0.0     2.0   1725.55230
2   28     1.0  33.000         3     0.0     2.0   4449.46200
3   33     1.0  22.705         0     0.0     1.0  21984.47061
4   32     1.0  28.880         0     0.0     1.0   3866.85520

# One Hot Encoding(Easy)


In [138]:
df12.head()

age  gender     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [139]:
df12_cat = df12.select_dtypes(np.object_)
df12_num = df12.select_dtypes(np.number)

In [140]:
df12_cat.head()

gender smoker     region
0  female    yes  southwest
1    male     no  southeast
2    male     no  southeast
3    male     no  northwest
4    male     no  northwest

In [142]:
df12_num.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

In [143]:
dummy6=pd.get_dummies(df12_cat,dtype=int)
dummy6.head()

gender_female  gender_male  smoker_no  smoker_yes  region_northeast  \
0              1            0          0           1                 0   
1              0            1          1           0                 0   
2              0            1          1           0                 0   
3              0            1          1           0                 0   
4              0            1          1           0                 0   

   region_northwest  region_southeast  region_southwest  
0                 0                 0                 1  
1                 0                 1                 0  
2                 0                 1                 0  
3                 1                 0                 0  
4                 1                 0                 0

In [150]:
df12.drop(['gender','smoker','region'],axis=1,inplace=True)

In [151]:
df12.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

# Dummy Variable Trap

In [153]:
dummy6=pd.get_dummies(df12_cat,dtype=int,drop_first=True)
dummy6.head()

gender_male  smoker_yes  region_northwest  region_southeast  \
0            0           1                 0                 0   
1            1           0                 0                 1   
2            1           0                 0                 1   
3            1           0                 1                 0   
4            1           0                 1                 0   

   region_southwest  
0                 1  
1                 0  
2                 0  
3                 0  
4                 0

In [159]:
df12=pd.concat([df12_num,dummy6],axis=1)
df12.head()


age     bmi  children      charges  gender_male  smoker_yes  \
0   19  27.900         0  16884.92400            0           1   
1   18  33.770         1   1725.55230            1           0   
2   28  33.000         3   4449.46200            1           0   
3   33  22.705         0  21984.47061            1           0   
4   32  28.880         0   3866.85520            1           0   

   region_northwest  region_southeast  region_southwest  
0                 0                 0                 1  
1                 0                 1                 0  
2                 0                 1                 0  
3                 1                 0                 0  
4                 1                 0                 0