# KNN Regressor:
# 1.import dataset
# 2.separete x,y
# 3.train, test
# 4.apply linear regrassion
# 5.evaluate model apply KNN regrassion evaluate model

In [15]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Height-Weight.xlsx to Height-Weight.xlsx


In [4]:
df=pd.read_excel('Height-Weight.xlsx')

In [5]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [6]:
df1=df.copy()
df2=df.copy()
df3=df.copy()

In [7]:
df.describe()

Height       Weight
count  8555.000000  8555.000000
mean     66.809925   165.632735
std       3.851454    32.043922
min      54.616858    65.780000
25%      63.957684   139.876803
50%      66.985923   168.521567
75%      69.604427   190.666305
max      80.450000   269.989698

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   object 
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), object(1)
memory usage: 200.6+ KB


In [9]:
df.shape

(8555, 3)

In [10]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

# Lable Encoder


In [12]:
df.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [13]:
from pandas.core.dtypes.common import is_numeric_dtype
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for col in df.columns:
  if is_numeric_dtype(df[col]):
    continue
  else:
    df[col]=le.fit_transform(df[col])

In [14]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

# Scaling

In [16]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()

In [17]:
df['Height']=mm.fit_transform(df[['Height']])

In [18]:
df.head()

Gender    Height      Weight
0       1  0.744399  241.893563
1       1  0.548328  162.310473
2       1  0.754583  212.740856
3       1  0.662487  220.042470
4       1  0.590905  206.349801

# Separete x,y

In [19]:
x=df.drop('Weight',axis=1)

In [20]:
x.head()

Gender    Height
0       1  0.744399
1       1  0.548328
2       1  0.754583
3       1  0.662487
4       1  0.590905

In [21]:
y=df[['Weight']]

In [22]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

# Split Train and Test

In [23]:
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression

In [24]:
x_train,x_test,y_train,y_test =tts(x,y,test_size=0.3,random_state=43)

In [25]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5988, 2), (2567, 2), (5988, 1), (2567, 1))

In [26]:
x_train.head()

Gender    Height
3024       1  0.544752
2815       1  0.482287
3573       1  0.682669
4071       1  0.516686
7055       0  0.376154

In [27]:
y_train.head()

Weight
3024  180.932596
2815  203.493687
3573  193.487309
4071  173.911384
7055  138.739445

# Apply Linear Regression

In [28]:
ln=LinearRegression()

In [29]:
ln.fit(x_train,y_train)

LinearRegression()

In [30]:
pred=ln.predict(x_test)
pred

array([[151.41873971],
       [149.69318918],
       [215.70009487],
       ...,
       [192.7095274 ],
       [170.86737583],
       [190.47063296]])

In [31]:
ln.predict([[0,0.356]])

array([[136.45600549]])

#Accuracy,MSE,MAE


In [32]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [34]:
accuracy_score=r2_score(y_test,pred)
accuracy_score

0.9009521883514205

In [35]:
mae=mean_absolute_error(y_test,pred)
mae

8.117437752642015

In [36]:
mse=mean_squared_error(y_test,pred)
mse

102.90497763129089

# Apply KNN Regression

In [37]:
from sklearn.neighbors import KNeighborsRegressor

In [39]:
ne=KNeighborsRegressor(n_neighbors=5)   #n_neighbors = 5 by defult

In [40]:
ne.fit(x_train,y_train)

KNeighborsRegressor()

In [41]:
kntest=ne.predict(x_test)
kntest

array([[149.9533951 ],
       [141.37455864],
       [219.94944548],
       ...,
       [194.7020528 ],
       [167.49885316],
       [182.26503844]])

In [42]:
ne.predict([[0,0.356]])

array([[138.41766014]])

# Evaluate Model


In [43]:
r2_score(y_test,kntest)

0.8784432335742146

In [44]:
mse=mean_squared_error(y_test,kntest)
mse

126.29048660215308

In [45]:
mae=mean_absolute_error(y_test,kntest)
mae

8.926880661887807